BEGIN;

DROP TABLE IF EXISTS runner;
DROP TABLE IF EXISTS race;

DROP TABLE IF EXISTS course;

DROP TABLE IF EXISTS horse;
DROP TABLE IF EXISTS trainer;
DROP TABLE IF EXISTS jockey;
DROP TABLE IF EXISTS owner;
DROP TABLE IF EXISTS region;

COMMIT;
