BEGIN;
        INSERT INTO
                region(region_id, region_code, name)
        VALUES
                (1,  'gb', 'Great Britain'),
                (2,  'ire', 'Ireland'),
                (3,  'arg', 'Argentina'),
                (4,  'aus', 'Australia'),
                (5,  'aut', 'Austria'),
                (6,  'bar', 'Barbados'),
                (7,  'bel', 'Belgium'),
                (8,  'bhr', 'Bahrain'),
                (9,  'brz', 'Brazil'),
                (10,  'bul', 'Bulgaria'),
                (11,  'can', 'Canada'),
                (12,  'chi', 'Chile'),
                (13,  'chn', 'China'),
                (14,  'cyp', 'Cyprus'),
                (15,  'cze', 'Czech Republic'),
                (16,  'den', 'Denmark'),
                (17,  'fr', 'France'),
                (18,  'ger', 'Germany'),
                (19,  'gr', 'Greece'),
                (20,  'gue', 'Guernsey'),
                (21,  'hk', 'Hong Kong'),
                (22,  'hol', 'Holland'),
                (23,  'hun', 'Hungary'),
                (24,  'ind', 'India'),
                (25,  'isr', 'Israel'),
                (26,  'ity', 'Italy'),
                (27,  'jer', 'Jersey'),
                (28,  'jpn', 'Japan'),
                (29,  'kor', 'Korea'),
                (30,  'ksa', 'Saudi Arabia'),
                (31,  'mac', 'Macau'),
                (32,  'mal', 'Malaysia'),
                (33,  'mau', 'Mauritius'),
                (34,  'mor', 'Morocco'),
                (35,  'nor', 'Norway'),
                (36,  'nz', 'New Zealand'),
                (37,  'omn', 'Oman'),
                (38,  'pan', 'Panama'),
                (39,  'per', 'Peru'),
                (40,  'pol', 'Poland'),
                (41,  'pr', 'Puerto Rico'),
                (42,  'qa', 'Qatar'),
                (43,  'rus', 'Russia'),
                (44,  'saf', 'South Africa'),
                (45,  'sin', 'Singapore'),
                (46,  'slo', 'Slovakia'),
                (47,  'spa', 'Spain'),
                (48,  'svn', 'Slovenia'),
                (49,  'swe', 'Sweden'),
                (50,  'swi', 'Switzerland'),
                (51,  'tur', 'Turkey'),
                (52,  'uae', 'United Arab Emirates'),
                (53,  'uru', 'Uruguay'),
                (54,  'usa', 'USA'),
                (55,  'yug', 'Yugoslavia');

COMMIT;

