#! /bin/bash

# Update README dir svg on change to git repo structure
if git st --porcelain -uno | grep -e '^R' -e '^D' -e '^A' &> /dev/null
then
        # generate svg
	eza --long --tree --level 4 -I tools -I vendor --git-ignore --no-user --no-time | svgbob --scale 1.5 --font-size 21 --font-family 'courier new' --background transparent > assets/dir.svg

        # add to commit
	git add assets/dir.svg
fi
