#! /bin/bash

FNAME=$1
CRS=7

echo > $FNAME

seq 2008 2022 | while read Y
do
        echo "./rpscrape.py -c $CRS -y $Y -t flat" >> $FNAME
done

cat $FNAME | shuf -o $FNAME


# TODO intersperse with vpn connect/disconnect every x(10?) lines

