#! /bin/bash

json=$(cat tools/rpscrape/courses/_temp | jq "to_entries")

# TODO, change double quotes to single quotes.
# * Ensure names contain a single quote aren't change e.g. "L'maine" should be 'L'maine'

# skip 'all' key at index 0 i.e. start at index 1
for index in $(seq 1 52)
do
       echo $json | jq ".[$index] | .value" \
                | sed 's/[{,}]//gm;s/:/,/gm;s/"//;s/"//;/^$d' \
                | awk -v i="$index" '{ print $0 ",", i }'

done

